<?php $_orders = $block->getOrders(); ?>
<?php $block->getChildHtml('info'); ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php echo __('Date') ?></th>
                <?php echo $block->getChildHtml('extra.column.header'); ?>
                <th scope="col" class="col shipping"><?php echo __('Ship To') ?></th>
                <th scope="col" class="col total"><?php echo __('Order Total') ?></th>
                <th scope="col" class="col status"><?php echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /** @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /** @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra): ?>
                        <?php $extra->setOrder($_order); ?>
                        <?php echo $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php echo $_order->getStatusLabel() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php echo $block->getViewUrl($_order) ?>" class="action view">
                            <span><?php echo __('View Order') ?></span>
                        </a>
                        <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?php
                            echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?php echo __('Reorder') ?></span>
                            </a>
                        <?php endif ?>
                        <?php if ($this->helper(\Perspective\CancelOrder\Helper\Data::class)->getStatusModule()) : ?>
                        <?php if ($this->helper(\Perspective\CancelOrder\Helper\Data::class)->getOrderStatus($_order->getStatusLabel())) : ?>
                        <a href="#<?= $_order->getRealOrderId() ?>" id="button">
                            <span><?= __('Cancel') ?></span>
                        </a>
                        <div id="modal" style="display:none;">
                            <h4 style="text-align: center">Your request will be solved in 48 hours</h4>
                            <label for="reason" class="reason - required">Choose a reason for order cancellation</label>
                            <select id="reason">
                                <option>I placed a duplicated order</option>
                                <option>I have changed</option>
                                <option>I found a cheaper</option>
                                <option>Other</option>
                            </select>
                            <label for="comment">Leave a comment</label><textarea id="comment"></textarea>
                        </div>
                        <script type="text/javascript">
                            require(
                                [
                                    'jquery',
                                    'Magento_Ui/js/modal/modal'
                                ],
                                function(
                                    $,
                                    modal
                                ) {
                                    var options = {
                                        type: 'popup',
                                        responsive: true,
                                        innerScroll: true,
                                        title: "<div style='text-align: center'>Cancel order</div>",
                                        buttons: [{
                                            text: $.mage.__('Cancel'),
                                            class: '',
                                            click: function () {
                                                this.closeModal();
                                            }
                                        },
                                            {
                                                text: $.mage.__('Submit'),
                                                class: '',
                                                click: function () {
                                                    let id = $("#button").attr("href");
                                                    let comment = $("#comment").val();
                                                    let reason = $("#reason").val();
                                                    $.ajax({
                                                        url: "http://study.loc/sales/order/cancel",
                                                        type: "POST",
                                                        data: {"id": id, "comment": comment, "reason": reason},
                                                    });
                                                    this.closeModal();
                                                    location.reload();
                                                }
                                            }
                                        ]
                                    };

                                    var popup = modal(options, $('#modal'));
                                    $("#button").on('click',function(){
                                        $("#modal").modal("openModal");
                                    });

                                }
                            );
                        </script>
                        <?php endif ?>
                        <?php endif ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /** @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
<?php endif ?>
