<?php /** @var \Perspective\Prices\Block\Price $block*/?>

<?php

$settingsArray = $block->getSettingsArray();
$priceArray = $block->getPrices();
if ($settingsArray[0]) {
    if (count($priceArray) > 5) {
        $product = $priceArray[5];
    }
    if (isset($product)) {
        ?>
        <p>Цена всего продукта без скидки <?php echo $priceArray[0];?></p>
        <p>Цена всего продукта со скидкой <b>15 % </b><?php echo $priceArray[4];?></p>
        <p>Цена выбраного продукта: <?php echo $priceArray[1];?></p>
        <?php
    } else {
        if ($settingsArray[2]) {
            ?>
            <p>Final price: <?php echo $priceArray[1];?></p>
            <?php
        } ?>
        <?php
    }
    if ($settingsArray[1]) { ?>
        <p>Base price: <?php echo $priceArray[0];?></p>
    <?php }
    if ($settingsArray[3]) {
        ?>
        <p>Special price: <?php echo $priceArray[2];?></p>
        <?php
    }
    if ($settingsArray[4]) {?>
        <p>Tier price: <?php echo $priceArray[3];?></p>
    <?php }
    if ($settingsArray[5]) {
        ?>
        <p>Catalog rule price: <?php echo $priceArray[4];?></p>
        <?php
    }
}
